import type { MindOverview } from "./runtimeTypes";

/** CNexus Product — 离线 Demo 数据（与 /v1/mind/overview 契约一致） */
export const DEMO_MIND_OVERVIEW: MindOverview = {
  schema_version: "1.0.0-demo",
  generated_at: new Date().toISOString(),
  goal_layer: {
    synthesis_generation: 1,
    active_goal_count: 2,
    conflicts: [],
  },
  cards: {
    goal: {
      title: "构建稳定认知系统",
      progress: 0.32,
      progress_label: "32%",
      alignment: 0.88,
      alignment_label: "88%",
      priority: 0.85,
      priority_label: "高",
    },
    identity: {
      summary: "我是一个持续探索与创造的学习者",
      stability: 0.92,
      stability_label: "92%",
      consistency: 0.85,
      consistency_label: "85%",
      updated_ago: "2h ago",
    },
    belief: {
      content: "长期稳定性优先于短期功能扩张",
      confidence: 0.82,
      confidence_label: "82%",
      evidence_count: 17,
      conflict_count: 0,
    },
    focus: {
      title: "完善 Meta-Cognition 与 Goal 联动",
      attention_label: "高",
      duration_label: "3天",
      related_goals: 2,
    },
  },
  feeds: {
    episodic: [
      { text: "优化了 BeliefMeta 设计", ago: "2h ago" },
      { text: "完成 Goal Layer 验证", ago: "5h ago" },
      { text: "修复 Memory 写入路径", ago: "1d ago" },
    ],
    reflections: [
      { text: "Reflection on goal consistency", ago: "3h ago" },
      { text: "Reflection on belief conflict", ago: "6h ago" },
    ],
    changes: [
      "Demo mode — 无 Runtime 绑定",
      "Belief confidence +7%",
      "Goal alignment +4%",
    ],
  },
  system: {
    health_score: 0.85,
    health_label: "Demo",
    memory_capacity_pct: 42,
    governance_label: "演示数据",
    governance_conflicts: 0,
    reflective_active: 2,
    last_update_ago: "静态",
    api_online: false,
  },
  chat_context: {
    goal: "构建稳定认知系统",
    belief: "长期稳定性优先于短期功能扩张",
    identity: "探索型学习者",
  },
  memory_items: [
    {
      id: "demo-goal-1",
      title: "构建稳定认知系统",
      tag: "goal",
      desc: "长期目标 · Progress 32%",
      meta: "Progress: 32%",
    },
    {
      id: "demo-belief-1",
      title: "长期稳定性优先于短期功能扩张",
      tag: "belief",
      desc: "核心信念 · Confidence 82%",
      meta: "Confidence: 82%",
    },
    {
      id: "demo-episode-1",
      title: "Goal Layer 验证完成",
      tag: "episode",
      desc: "情节记忆 · 2h ago",
      meta: "2h ago",
    },
    {
      id: "demo-identity-1",
      title: "探索型学习者",
      tag: "identity",
      desc: "身份描述 · Stability 92%",
      meta: "Stability: 92%",
    },
  ],
  personality: {
    emotion: {
      primary_emotion: "curiosity",
      primary_emotion_label: "好奇",
      intensity: 0.68,
      intensity_label: "68%",
      valence: 0.42,
      valence_label: "正向",
      arousal: 0.55,
      arousal_label: "55%",
      dominance: 0.61,
      dominance_label: "61%",
      last_updated_ago: "12 min ago",
    },
    dna: {
      traits: [
        { key: "curiosity", label: "好奇心", value: 0.75, value_label: "75%" },
        { key: "empathy", label: "共情", value: 0.78, value_label: "78%" },
        { key: "humor", label: "幽默", value: 0.65, value_label: "65%" },
        { key: "openness", label: "开放性", value: 0.82, value_label: "82%" },
        { key: "loyalty", label: "忠诚", value: 0.88, value_label: "88%" },
        { key: "patience", label: "耐心", value: 0.7, value_label: "70%" },
        { key: "assertiveness", label: "果断", value: 0.6, value_label: "60%" },
        { key: "emotional_stability", label: "情绪稳定", value: 0.85, value_label: "85%" },
        { key: "risk_tolerance", label: "风险承受", value: 0.45, value_label: "45%" },
        { key: "self_consistency", label: "自我一致", value: 0.92, value_label: "92%" },
      ],
      version: "5.0.0",
      mutation_count: 0,
      self_consistency: 0.92,
      self_consistency_label: "92%",
      overall_stability: 0.88,
      overall_stability_label: "88%",
      last_updated_ago: "静态",
    },
    identity: {
      summary: "我是一个持续探索与创造的学习者",
      stability: 0.92,
      stability_label: "92%",
      consistency: 0.85,
      consistency_label: "85%",
      updated_ago: "2h ago",
    },
    belief: {
      content: "长期稳定性优先于短期功能扩张",
      confidence: 0.82,
      confidence_label: "82%",
      evidence_count: 17,
      conflict_count: 0,
    },
  },
  intent: {
    current_focus_id: "demo-goal-1",
    current_focus_label: "完善 Meta-Cognition 与 Goal 联动",
    motivation_baseline: 0.72,
    motivation_baseline_label: "72%",
    active_goal_count: 2,
    goals: [
      {
        goal_id: "demo-goal-1",
        description: "构建稳定认知系统",
        priority: 0.85,
        priority_label: "高",
        motivation: 0.78,
        motivation_label: "78%",
        alignment_score: 0.88,
        alignment_label: "88%",
        progress: 0.32,
        progress_label: "32%",
        status: "active",
      },
      {
        goal_id: "demo-goal-2",
        description: "完善 Meta-Cognition 与 Goal 联动",
        priority: 0.72,
        priority_label: "高",
        motivation: 0.71,
        motivation_label: "71%",
        alignment_score: 0.84,
        alignment_label: "84%",
        progress: 0.48,
        progress_label: "48%",
        status: "active",
      },
    ],
    proactive: {
      should_trigger: true,
      reason: "高动机目标推进：完善 Meta-Cognition 与 Goal 联动",
      suggested_action: "要不要我帮你推进「完善 Meta-Cognition 与 Goal 联动」这个目标？",
      priority: 0.6,
      priority_label: "60%",
      goal_id: "demo-goal-2",
    },
    last_updated_ago: "18 min ago",
  },
};
