import type { SpineEvent } from "./spineTypes";

const BASE = Date.now() - 120_000;

export const DEMO_SPINE_EVENTS: SpineEvent[] = [
  {
    event_id: "e-dispatch-1",
    trace_id: "trace-8f3a2c1d",
    timestamp: BASE,
    event_type: "dispatch",
    subsystem: "runtime",
    action: "read",
    summary: "chat request dispatched · entry process_interaction",
    provenance: { caller: "http", channel: "brain-memory-ui", entry_registry: "process_interaction", dispatch_kind: "chat" },
    decision: { decision: "ALLOW", entry: "process_interaction", caller: "http", hard_gate: false },
  },
  {
    event_id: "e-recall-1",
    trace_id: "trace-8f3a2c1d",
    timestamp: BASE + 1200,
    event_type: "recall",
    subsystem: "runtime",
    action: "read",
    parent_event_id: "e-dispatch-1",
    causal_links: ["e-dispatch-1"],
    summary: "memory recall · top_k=6 · implicit side-effect",
    write_intent: { intent_id: "tx-recall-01", kind: "recall_side_effect", mutability: "implicit", shadow: true, phase: "proposal" },
    provenance: { caller: "http", channel: "brain-memory-ui", entry_registry: "memory_recall" },
    decision: { decision: "WARN", entry: "memory_recall", caller: "http", hard_gate: false, reason: "shadow emit" },
    state_delta: { working_self: ["context buffer += recall hits"] },
  },
  {
    event_id: "e-cdg-1",
    trace_id: "trace-8f3a2c1d",
    timestamp: BASE + 3400,
    event_type: "cdg",
    subsystem: "cdg",
    action: "propose",
    parent_event_id: "e-recall-1",
    causal_links: ["e-recall-1"],
    summary: "CDG advisory apply · no mutation",
    write_intent: { intent_id: "tx-cdg-01", kind: "cdg_apply", mutability: "advisory", shadow: true, phase: "proposal" },
    provenance: { caller: "internal", channel: "cdg", entry_registry: "cdg_cycle" },
    decision: { decision: "ALLOW", entry: "cdg_cycle", caller: "internal", hard_gate: false },
  },
  {
    event_id: "e-capture-1",
    trace_id: "trace-8f3a2c1d",
    timestamp: BASE + 8200,
    event_type: "capture",
    subsystem: "gtbs",
    action: "commit",
    parent_event_id: "e-cdg-1",
    causal_links: ["e-cdg-1"],
    summary: "capture · explicit write · committed",
    write_intent: { intent_id: "tx-cap-01", kind: "capture", mutability: "explicit", shadow: false, phase: "commit" },
    provenance: { caller: "http", channel: "brain-memory-ui", entry_registry: "capture_direct" },
    decision: { decision: "ALLOW", entry: "capture_direct", caller: "http", hard_gate: false },
    state_delta: { memory: ["+1 episodic item"], graph: ["edge linked to goal"] },
  },
  {
    event_id: "e-control-1",
    trace_id: "trace-legacy-99",
    timestamp: BASE + 15_000,
    event_type: "control",
    subsystem: "control_plane",
    action: "reject",
    summary: "legacy_api entry · REJECT · hard gate",
    provenance: { caller: "legacy_api", channel: "legacy", entry_registry: "legacy_write" },
    decision: { decision: "REJECT", entry: "legacy_write", caller: "legacy_api", hard_gate: true, reason: "UNKNOWN_ENTRY" },
  },
  {
    event_id: "e-dispatch-2",
    trace_id: "trace-b2e91f0a",
    timestamp: BASE + 22_000,
    event_type: "dispatch",
    subsystem: "runtime",
    action: "read",
    summary: "websocket stream · analyze path",
    provenance: { caller: "websocket", channel: "ws", entry_registry: "cse_synthesize" },
    decision: { decision: "ALLOW", entry: "cse_synthesize", caller: "websocket", hard_gate: false },
  },
  {
    event_id: "e-write-2",
    trace_id: "trace-b2e91f0a",
    timestamp: BASE + 24_500,
    event_type: "write_intent",
    subsystem: "gtbs",
    action: "propose",
    parent_event_id: "e-dispatch-2",
    causal_links: ["e-dispatch-2"],
    summary: "working_self update · implicit · shadow",
    write_intent: { intent_id: "tx-ws-02", kind: "working_self", mutability: "implicit", shadow: true, phase: "proposal" },
    provenance: { caller: "websocket", channel: "ws", entry_registry: "working_self_sync" },
    decision: { decision: "WARN", entry: "working_self_sync", caller: "websocket", hard_gate: false, reason: "shadow emit" },
    state_delta: { working_self: ["focus weight adjusted"] },
  },
];
